# Name of the workflow
name: First Workflow

# Trigger 
on: 
  pull_request:
    types:
     - opened
     - synchronize  
jobs:
  build: # job name
    runs-on: ubuntu-latest   # github hosted runner
    steps:
     - name: code checkout
       run: echo " Welcome"
     - name: Setup 
       run: echo " Second step"
  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Echo 
        run: echo " Welcome to first workflow"
