# Name of the workflow
name: First Workflow

# Trigger 
on: 
 push   # event
 
jobs:
  build: # job name
    runs-on: ubuntu-latest   # github hosted runner
    steps:
     - name: Echo 
       run: echo " Welcome to first workflow"
  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Echo 
        run: echo " Welcome to first workflow"
