# Name of the workflow
name: First Workflow

run-name: DEBUG| ${{inputs.debug}}

# Trigger 
on: 
 workflow_dispatch:
  inputs:
   debug:
    type: boolean
    default: false

jobs:
  build: # job name
    runs-on: ubuntu-latest   # github hosted runner
    steps:
     - name: code checkout
       run: echo " Welcome"
     - name: Setup 
       run: exit 1
  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Echo 
        run: echo " Welcome to first workflow"
